FROM node:22.14-alpine

RUN apk update && apk add git curl \
    && rm -rf /var/cache/apk/* \
    && npm install -g npm

WORKDIR /usr/src/app

# Copy dependency files
COPY ./source/package*.json .

# Install all dependencies
RUN npm ci